- app/assets/javascripts/transaction_list.js
- app/models/Transaction.java
- app/views/all_transactions.scala.html
Just needed to add a small feature.
> Add checkbox to All Transactions page to hide non-personal transactions

- app/controllers/Attendance.java
- app/models/AttendanceStats.java
Fix bug where "no school" days were being counted as absences for the attendance percent calculation
> Attendance rate bug fix

- app/assets/checkin/app.html
- app/assets/checkin/app.js
- app/assets/checkin/service-worker.js
- app/assets/checkin/style.css
- app/controllers/Checkin.java
- app/views/attendance_pins.scala.html
- conf/routes
There are a couple of bugs I needed to fix in addition to the cosmetic changes. One of them is a time zone bug I don't quite understand. It works fine for me locally, but on the live site it's persisting times in UTC. It seems that java.sql.Time implicitly converts milliseconds since epoch to the server local time? I created a fix, but I can't know if it works or not until it's deployed.
> Checkin app fix

- app/assets/checkin/service-worker.js
Oops! I forgot to update the cache version when I fixed that bug, so it's not actually downloading the new code.
> Update cache version

- app/assets/checkin/service-worker.js
Thanks for your timeliness on the recent updates. This one's a bit lower priority. I'm changing the caching strategy so the client will immediately get the new version of the app when they refresh.
> Change caching strategy

- app/assets/checkin/app.html
- app/assets/checkin/app.js
- app/assets/checkin/service-worker.js
- app/assets/checkin/style.css
- app/controllers/Attendance.java
- app/controllers/Checkin.java
- app/models/CheckinData.java
- app/models/Organization.java
- conf/evolutions/default/82.sql
- conf/routes
This is a new feature which allows an admin to edit attendance data within the app. First the user needs to go to the Assign PINs page and create an admin PIN. Then in the app, they can enter this code and hit any button to access an editable version of the Roster.
> Checkin app edit mode

- app/assets/checkin/app.js
- app/assets/checkin/service-worker.js
This is a bug fix for the checkin app edit mode.
> Ignore admin code if it's empty

- app/controllers/Accounting.java
- app/models/Account.java
- app/views/balances.scala.html
- app/views/edit_account.scala.html
- conf/evolutions/default/85.sql
Allow deactivating accounts so they won't show up in the Balances page or Create Transactions page
> Accounting deactivate accounts

- app/assets/checkin/app-compiled.js
- app/assets/checkin/app.js
- app/assets/checkin/service-worker.js
I've made it so that when a user signs in or out, it records the time rounded down to the minute. This is so that if the arrival cutoff is 11:00, and a student arrives at 11:00:30, they are not considered late. This is how people expect the app to work.
> Checkin app round down to the minute

- app/models/AttendanceDay.java
- app/models/Organization.java
- app/views/view_settings.scala.html
- conf/evolutions/default/91.sql
I've edited the attendance setting "minimum hours for a full day" so that it accepts decimal values.
> Change attendance_day_min_hours from integer to double

- app/models/OrgConfig.java
- app/views/edit_minutes.scala.html
I wanted to have an option for the plea to be "Mediated". Since there is already an option called N/A, I added a setting to change the text of the N/A plea, and changed it for The Open School.
> Add option to change text of N/A plea

- app/controllers/Checkin.java
This is a change to the way the Checkin app works. Now if someone signs in or out, it overwrites any existing absence code.
> Make arrival/departure messages from checkin app overwrite absence codes

- app/models/AttendanceStats.java
Instead of doing a rollback, you can just push this change which fixes the error.
> Fix null reference exception

- app/controllers/Attendance.java
> Another fix for null reference exception

- app/controllers/Attendance.java
@aaronbrowder This fixes the single person attendance page for me. I'm not sure why it was working properly for you, but maybe we are running with different versions of the JVM? 
SIde note: Do you want to include the weighted attendance rate on that page as well?
> Fix person attendance page

- app/assets/stylesheets/main.less
- app/views/attendance_index.scala.html
This reverts commit 445590be562946ccf9c0fd9b0f6968a7c2d8c1b3.
> Restore the old way of highlighting rows in attendance index table

- app/models/TransactionList.java
Sorry, I made a mistake with the previous update. Sorting by date is not enough -- I need to sort by date then by ID.
> Attempt #2 to fix bug with bank cash balance

- app/assets/stylesheets/main.less
- app/controllers/Application.java
- app/controllers/ApplicationEditing.java
- app/views/main.scala.html
- app/views/view_meeting.scala.html
- conf/routes
This also fixes the date that is used in "edit today's minutes" so that it uses the school's time zone instead of UTC to determine today's date.
> Add "view today's minutes" link

- app/controllers/Application.java
- app/models/TransactionList.java
- app/views/transactions_report.scala.html
- modelsLibrary/app/models/Account.java
- modelsLibrary/app/models/Transaction.java
- Add date range to transactions report
- Fix bug where people would not get assigned accounts if they were not tagged "current student" at the time accounting feature was turned on
> Accounting fix 3

- app/assets/javascripts/attendance_rule.js
- app/assets/javascripts/main.js
- app/views/attendance_edit_rule.scala.html
- Fix bug where person name would be blank when opening an existing attendance rule
- Fix bug where an attendance rule referencing a deactivated person would not show the person name
> Attendance rules fixes

- app/assets/stylesheets/main.less
- app/models/RolesReport.java
- Fix NullPointerException that was happening when the roles report is run
- Prevent text wrapping in Roles table, so row height doesn't change when opening the editor
> Roles fixes

- .prettierrc
- app/assets/javascripts/attendance_person.js
- app/assets/javascripts/attendance_rule.js
- app/assets/javascripts/autocomplete.js
- app/assets/javascripts/chooser.js
- app/assets/javascripts/create_transaction.js
- app/assets/javascripts/edit_attendance_week.js
- app/assets/javascripts/edit_entry.js
- app/assets/javascripts/edit_minutes.js
- app/assets/javascripts/edit_rp_list.js
- app/assets/javascripts/feedback_modal.js
- app/assets/javascripts/main.js
- app/assets/javascripts/off_campus.js
- app/assets/javascripts/people_chooser.js
- app/assets/javascripts/roles.js
- app/assets/javascripts/settings_page.js
- app/assets/javascripts/sorttable.js
- app/assets/javascripts/transaction_list.js
- app/assets/javascripts/utils.js
- app/assets/stylesheets/main.less
- app/views/attendance_week.scala.html
If just one start time or end time is missing, show the one that is present instead of showing three question marks. If both start time and end time are missing, show an emdash instead of triple question marks. 
Save on blur, so it's not so easy to accidentally not save the last entry you made in the week editor.
Highlight invalid absence codes in red.
> Improve saving and error messages in attendance week editor

- django/demschooltools/auth.py
- django/demschooltools/settings.py
- django/demschooltools/settings_prod.py
- django/pyproject.toml
- django/uv.lock
FYI @angusmccloud my last PR broke the Django pages in local development, but this fixes it now.
> Use .env file in Python too
